pipeline {
    agent { node { label 'maven' } }
    options { skipDefaultCheckout true }
    stages {
        stage('Checkout') {
            steps {
		sendNotification('Started', 'test@example.com')
                git branch: 'notifications',
                    url: 'https://github.com/chris1867/DO400-apps'
            }
        }
        stage('Test') {
            steps {
                dir('simple-calculator') {
                    sh './mvnw clean test'
                }
            }
        }
    }
    post {
	always {
	    sendNotification('finished', 'test@example.com')
	}
    }
}
void sendNotification(String action, String email) {
    mail to: "${email}",
        subject: "Pipeline ${action}: ${currentBuild.fullDisplayName}",
        body: "The following pipeline ${action}: ${env.BUILD_URL}"
}

